name: CI/CD - HelloServlet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (for mvn test step)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Maven tests
        run: mvn -B -DskipTests=false test
        # If tests require env vars or DB, add them here.

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/hello-servlet:${{ github.sha }}
          docker build -t $IMAGE .
          docker tag $IMAGE ${{ secrets.DOCKERHUB_USERNAME }}/hello-servlet:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Push image (both sha and latest)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-servlet:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-servlet:latest
